
// Parser generated by Maphoon 2008


#line 1



// Non-terminal symbols:







   // Contains the stored variables.

#include "varstore.h"
#include "tree.h"

#include "assert.h"
#include <math.h>

















#include "token.h"
#include "tokenizer.h"
#include "parser.h"

#include <cstdlib>




// Code generated by Maphoon 2008C
// Written by Hans de Nivelle, June 2008 - May 2010
// See the licence that was included with the code. 



namespace
{
   struct refused
   {
   };

   std::ostream& operator << ( std::ostream& stream, refused ref )
   {
      stream << "REFUSED";
      return stream;
   }
}



namespace
{

// Here come the tables:

   unsigned int starts [] = 
   {
      0, 5, 29, 31, 38, 41, 55, 57, 63, 65, 71, 
      78, 81, 86, 89, 92, 94, 98, 103, 106, 109, 
      113, 115, 118, 122, 124, 126, 128, 131, 133, 140, 
      144, 147, 149, 156, 163, 166, 169, 172, 174, 177, 
      179, 186, 189, 0 };

   unsigned int defaults [] = {
      0, 1, 2, 3, 4, 5, 5, 5, 8, 9, 10, 
      11, 12, 13, 14, 7, 7, 17, 18, 19, 9, 
      21, 22, 5, 23, 5, 5, 27, 9, 29, 30, 
      31, 32, 33, 34, 35, 36, 37, 7, 39, 40, 
      41, 42, 0 };

   int parsetable [] = 
   {
      tkn__defaultred, -10002, 0, 
      tkn_Session, 10001, 
      tkn__recover, 10002, 
      tkn_IDENTIFIER, 10003, 
      tkn_NUMBER, 10004, 
      tkn_PLUS, 10005, 
      tkn_MINUS, 10006, 
      tkn_LPAR, 10007, 
      tkn_FUNKEYWORD, 10008, 
      tkn_E, 10009, 
      tkn_F, 10010, 
      tkn_G, 10011, 
      tkn_H, 10012, 
      tkn_Command, 10013, 
      tkn_SEMICOLON, 10014, 
      tkn__defaultred, -10018, 0, 
      tkn_BECOMES, 10015, 
      tkn_LPAR, 10016, 
      tkn__defaultred, -10019, 0, 
      tkn_IDENTIFIER, 10017, 
      tkn_NUMBER, 10004, 
      tkn_PLUS, 10005, 
      tkn_MINUS, 10006, 
      tkn_LPAR, 10007, 
      tkn_G, 10018, 
      tkn_H, 10012, 
      tkn_G, 10019, 
      tkn_E, 10020, 
      tkn_F, 10010, 
      tkn_G, 10011, 
      tkn_IDENTIFIER, 10021, 
      tkn_SEMICOLON, 10022, 
      tkn_PLUS, 10023, 
      tkn_MINUS, 10024, 
      tkn__defaultred, -10009, 0, 
      tkn_TIMES, 10025, 
      tkn_DIVIDES, 10026, 
      tkn__defaultred, -10012, 0, 
      tkn__defaultred, -10015, 0, 
      tkn_FACTORIAL, 10027, 
      tkn__defaultred, -10001, 0, 
      tkn__defaultred, -10006, 0, 
      tkn_E, 10028, 
      tkn_E, 10029, 
      tkn_LISTARGS, 10030, 
      tkn__defaultred, -10018, 0, 
      tkn_LPAR, 10016, 
      tkn__defaultred, -10014, 0, 
      tkn__defaultred, -10013, 0, 
      tkn_SEMICOLON, 0, 
      tkn_RPAR, 10031, 
      tkn_LPAR, 10032, 
      tkn__defaultred, -10003, 0, 
      tkn_F, 10033, 
      tkn_G, 10011, 
      tkn_F, 10034, 
      tkn_G, 10035, 
      tkn_G, 10036, 
      tkn__defaultred, -10016, 0, 
      tkn_SEMICOLON, 10037, 
      tkn__defaultred, -10021, 0, 
      tkn_PLUS, 10023, 
      tkn_MINUS, 10024, 
      tkn_COMMA, 10038, 
      tkn_RPAR, 10039, 
      tkn__defaultred, -10017, 0, 
      tkn_RPAR, 10040, 
      tkn__defaultred, -10007, 0, 
      tkn_TIMES, 10025, 
      tkn_DIVIDES, 10026, 
      tkn__defaultred, -10008, 0, 
      tkn_TIMES, 10025, 
      tkn_DIVIDES, 10026, 
      tkn__defaultred, -10010, 0, 
      tkn__defaultred, -10011, 0, 
      tkn__defaultred, -10004, 0, 
      tkn_E, 10041, 
      tkn__defaultred, -10020, 0, 
      tkn_SEMICOLON, 10042, 
      tkn__defaultred, -10022, 0, 
      tkn_PLUS, 10023, 
      tkn_MINUS, 10024, 
      tkn__defaultred, -10005, 0, 
   0 };

   int entrypoints [] = 
   {
      tkn_Session, 0, tkn_EOF, -1,
      -1
   };



}


namespace
{


   // There are two reduce functions.
   // 
   // The first returns a token from the parse stack.
   // The other tokens are removed, and it is checked that the
   // token has the right type.
   // 
   // The second returns a new token. All tokens from the parse stack
   // are removed, and the new token is pushed.

   void reduce( std::list< token > & parsestack,
                std::list< token > :: iterator position,
                tokentype expectedtype,
                std::list< token > :: const_iterator result )
   {
      ASSERT( result -> type == expectedtype );
         // Must be type of lhs. 
      ASSERT( result -> iswellformed( ));

      bool seen = false;
      while( position != parsestack. end( ))
      {
         if( position == result )
         {
            ASSERT( !seen );
            seen = true;
            ++ position;
         }
         else
         {
            std::list< token > :: iterator p1 = position;
            ++ position; 
            parsestack. erase( p1 );
         }
      }
      ASSERT( seen );
   }


   void reduce( std::list< token > & parsestack,
                std::list< token > :: iterator position,
                tokentype expectedtype,
                const token& result )
   {
      ASSERT( result. type == expectedtype ); 
      ASSERT( result. iswellformed( )); 

      while( position != parsestack. end( ))
      {
         ASSERT( & (*position) != & result );
            // If this happenes, the user typed 'return *T'
            // for an attribute variable. 
            // He should have typed 'return T' instead. 
  
         std::list< token > :: iterator p1 = position;
         ++ position;
         parsestack. erase( p1 ); 
      }

      parsestack. insert( position, result ); 
   }


   // This is not terribly efficient, but we expect the size of the
   // rules to be moderate.

   std::list< token > :: iterator 
   operator - ( std::list< token > :: iterator p,
                unsigned int diff )
   {
      while( diff > 0 )
      {
         -- diff; 
         -- p;
      }
      return p; 
   }


// Here come the actions:

void reduction_0(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator Session1,
   std::list < token > :: iterator EOF2 ) throw( refused )
{

#line 52 "calculator.m"

std::cout << "bye bye\n";
{ reduce( stack, position, tkn_Start, tkn_Start ); return; }

}


void reduction_1(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator Session1,
   std::list < token > :: iterator Command2 ) throw( refused )
{

#line 56 "calculator.m"


if( Command2 -> tree. size( )) {
std::cout << Command2 -> tree. front( ) << "\n";
} else {
std::cout << " Result is undefined\n";
}

{ reduce( stack, position, tkn_Session, tkn_Session ); return; }

}


void reduction_2(
   std::list < token > & stack,
   std::list < token > :: iterator position ) throw( refused )
{

#line 64 "calculator.m"

{ reduce( stack, position, tkn_Session, tkn_Session ); return; }

}


void reduction_3(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator E1,
   std::list < token > :: iterator SEMICOLON2 ) throw( refused )
{

#line 68 "calculator.m"


token t = tkn_Command;
tree newt = tree("compute");
if (E1 -> tree.size())
newt.pntr->subtrees.push_back(tree(E1 -> tree.front()));
t.tree.push_back(newt);
{ reduce( stack, position, tkn_Command, t ); return; }

{ reduce( stack, position, tkn_Command, tkn_Command ); return; }

}


void reduction_4(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator IDENTIFIER1,
   std::list < token > :: iterator BECOMES2,
   std::list < token > :: iterator E3,
   std::list < token > :: iterator SEMICOLON4 ) throw( refused )
{

#line 77 "calculator.m"


token t = tkn_Command;
tree newt = tree("assign");
if (IDENTIFIER1 -> id.size())
newt.pntr->subtrees.push_back(tree(IDENTIFIER1 -> id.front()));
if (E3 -> tree.size())
newt.pntr->subtrees.push_back(E3 -> tree.front());
t.tree.push_back(newt);
{ reduce( stack, position, tkn_Command, t ); return; }
{ reduce( stack, position, tkn_Command, tkn_Command ); return; }

}


void reduction_5(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator FUNKEYWORD1,
   std::list < token > :: iterator IDENTIFIER2,
   std::list < token > :: iterator LPAR3,
   std::list < token > :: iterator RPAR4,
   std::list < token > :: iterator SEMICOLON5 ) throw( refused )
{

#line 87 "calculator.m"


token t = tkn_Command;
tree newt = tree("FUN");
if (IDENTIFIER2 -> id.size())
newt.pntr->subtrees.push_back(tree(IDENTIFIER2 -> id.front()));
t.tree.push_back(newt);
{ reduce( stack, position, tkn_Command, t ); return; }

{ reduce( stack, position, tkn_Command, tkn_Command ); return; }

}


void reduction_6(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator _recover1,
   std::list < token > :: iterator SEMICOLON2 ) throw( refused )
{

#line 96 "calculator.m"


std::cout << "recovered from error\n\n";

{ reduce( stack, position, tkn_Command, tkn_Command ); return; }

}


void reduction_7(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator E1,
   std::list < token > :: iterator PLUS2,
   std::list < token > :: iterator F3 ) throw( refused )
{

#line 102 "calculator.m"


token t = tkn_E;
tree newt = tree("+");
if (E1 -> tree.size())
newt.pntr->subtrees.push_back(E1 -> tree.front());
if (F3 -> tree.size())
newt.pntr->subtrees.push_back(F3 -> tree.front());
t.tree.push_back(newt);
{ reduce( stack, position, tkn_E, t ); return; }

{ reduce( stack, position, tkn_E, tkn_E ); return; }

}


void reduction_8(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator E1,
   std::list < token > :: iterator MINUS2,
   std::list < token > :: iterator F3 ) throw( refused )
{

#line 113 "calculator.m"


token t = tkn_E;
tree newt = tree("-");
if (E1 -> tree.size())
newt.pntr->subtrees.push_back(E1 -> tree.front());
if (F3 -> tree.size())
newt.pntr->subtrees.push_back(F3 -> tree.front());
t.tree.push_back(newt);
{ reduce( stack, position, tkn_E, t ); return; }

{ reduce( stack, position, tkn_E, tkn_E ); return; }

}


void reduction_9(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator F1 ) throw( refused )
{

#line 124 "calculator.m"


// Change F into E, don't touch attribute.

F1 -> type = tkn_E;
{ reduce( stack, position, tkn_E, F1 ); return; }

{ reduce( stack, position, tkn_E, tkn_E ); return; }

}


void reduction_10(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator F1,
   std::list < token > :: iterator TIMES2,
   std::list < token > :: iterator G3 ) throw( refused )
{

#line 133 "calculator.m"


token t = tkn_F;
tree newt = tree("*");
if (F1 -> tree.size())
newt.pntr->subtrees.push_back(F1 -> tree.front());
if (G3 -> tree.size())
newt.pntr->subtrees.push_back(G3 -> tree.front());
t.tree.push_back(newt);
{ reduce( stack, position, tkn_F, t ); return; }

{ reduce( stack, position, tkn_F, tkn_F ); return; }

}


void reduction_11(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator F1,
   std::list < token > :: iterator DIVIDES2,
   std::list < token > :: iterator G3 ) throw( refused )
{

#line 144 "calculator.m"


token t = tkn_F;
tree newt = tree("/");
if (F1 -> tree.size())
newt.pntr->subtrees.push_back(F1 -> tree.front());
if (G3 -> tree.size())
newt.pntr->subtrees.push_back(G3 -> tree.front());
t.tree.push_back(newt);
{ reduce( stack, position, tkn_F, t ); return; }

{ reduce( stack, position, tkn_F, tkn_F ); return; }

}


void reduction_12(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator G1 ) throw( refused )
{

#line 155 "calculator.m"


G1 -> type = tkn_F;
{ reduce( stack, position, tkn_F, G1 ); return; }

{ reduce( stack, position, tkn_F, tkn_F ); return; }

}


void reduction_13(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator MINUS1,
   std::list < token > :: iterator G2 ) throw( refused )
{

#line 163 "calculator.m"


token t = tkn_G;
tree newt = tree("-");
if (G2 -> tree.size())
newt.pntr->subtrees.push_back(G2 -> tree.front());
t.tree.push_back(newt);
{ reduce( stack, position, tkn_G, t ); return; }

{ reduce( stack, position, tkn_G, tkn_G ); return; }

}


void reduction_14(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator PLUS1,
   std::list < token > :: iterator G2 ) throw( refused )
{

#line 172 "calculator.m"


{ reduce( stack, position, tkn_G, G2 ); return; }

{ reduce( stack, position, tkn_G, tkn_G ); return; }

}


void reduction_15(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator H1 ) throw( refused )
{

#line 176 "calculator.m"


H1 -> type = tkn_G;
{ reduce( stack, position, tkn_G, H1 ); return; }

{ reduce( stack, position, tkn_G, tkn_G ); return; }

}


void reduction_16(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator H1,
   std::list < token > :: iterator FACTORIAL2 ) throw( refused )
{

#line 184 "calculator.m"


token t = tkn_H;
tree newt = tree("!");
if (H1 -> tree.size())
newt.pntr->subtrees.push_back(H1 -> tree.front());
t.tree.push_back(newt);
{ reduce( stack, position, tkn_H, t ); return; }

{ reduce( stack, position, tkn_H, tkn_H ); return; }

}


void reduction_17(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator LPAR1,
   std::list < token > :: iterator E2,
   std::list < token > :: iterator RPAR3 ) throw( refused )
{

#line 193 "calculator.m"


E2 -> type = tkn_H;
{ reduce( stack, position, tkn_H, E2 ); return; }

{ reduce( stack, position, tkn_H, tkn_H ); return; }

}


void reduction_18(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator IDENTIFIER1 ) throw( refused )
{

#line 198 "calculator.m"


token h = tkn_H;
tree newt = tree("var");
newt.pntr->subtrees.push_back(tree(IDENTIFIER1 -> id.front()));
h.tree.push_back(newt);
{ reduce( stack, position, tkn_H, h ); return; }

{ reduce( stack, position, tkn_H, tkn_H ); return; }

}


void reduction_19(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator NUMBER1 ) throw( refused )
{

#line 206 "calculator.m"


token h = tkn_H;
tree newt = tree("num");
newt.pntr->subtrees.push_back(tree(NUMBER1 -> value.front()));
h.tree.push_back(newt);
{ reduce( stack, position, tkn_H, h ); return; }

{ reduce( stack, position, tkn_H, tkn_H ); return; }

}


void reduction_20(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator IDENTIFIER1,
   std::list < token > :: iterator LPAR2,
   std::list < token > :: iterator LISTARGS3,
   std::list < token > :: iterator RPAR4 ) throw( refused )
{

#line 214 "calculator.m"


token h = tkn_H;
std::vector<tree> strees = std::vector<tree>();
for (auto a : LISTARGS3 -> tree) {
strees.push_back(a);
}
tree newt = tree(IDENTIFIER1 -> id.front(), strees);
h.tree.push_back(newt);
{ reduce( stack, position, tkn_H, h ); return; }

{ reduce( stack, position, tkn_H, tkn_H ); return; }

}


void reduction_21(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator E1 ) throw( refused )
{

#line 228 "calculator.m"

token t = tkn_LISTARGS;
t.tree.push_back(E1 -> tree.front());
{ reduce( stack, position, tkn_LISTARGS, t ); return; }

{ reduce( stack, position, tkn_LISTARGS, tkn_LISTARGS ); return; }

}


void reduction_22(
   std::list < token > & stack,
   std::list < token > :: iterator position,
   std::list < token > :: iterator LISTARGS1,
   std::list < token > :: iterator COMMA2,
   std::list < token > :: iterator E3 ) throw( refused )
{

#line 233 "calculator.m"


LISTARGS1 -> tree.push_back(E3 -> tree.front());
{ reduce( stack, position, tkn_LISTARGS, LISTARGS1 ); return; }

{ reduce( stack, position, tkn_LISTARGS, tkn_LISTARGS ); return; }

}





   
   // The return values are specified as follows: 
   // 
   //                 0 : error.
   //        10000 + X  : push to state X.
   //        -10000 - X : Reduce rule X.
   // 
   // The returned list contains a sequence of reductions, terminated 
   // by an error or a push. 
   //
   // We try to base our decision on lookahead. If more lookahead
   // is required, we extend lookahead by doing: 
   //    lookahead. push_back( input. scan( ));
   

   std::list< int > decideaction( unsigned int ss, tokenizer& input )
   {
      std::list< int > result;

      unsigned int k = starts [ss];
      unsigned int defred = 0;
 
      while( true )
      {
         while( k == starts [ ss + 1 ] )
         {
            // This means that we reached the end.
            // If defaults [ss] != ss, we can continue looking in another
            // state.

            if( defaults [ss] == ss )
            {
               if( defred == 0 )
                  result. push_back(0);
               else
               {
                  result. push_back( defred ); 
                  result. push_back(0);
               }
               return result; 
            }

            ss = defaults [ ss ];
            k = starts [ ss ]; 
         }
          
         if( parsetable [k] == tkn__defaultred )
         {
            ASSERT( parsetable [ k+1 ] < 0 && parsetable [ k+2 ] == 0 );
            ASSERT( defred == 0 );
            defred = parsetable [ k + 1 ];
            k += 3; 
         }
         else
         {
            if( input. lookahead. size( ) == 0 )
            {
               input. scan( );
               ASSERT( input. lookahead. size( ));
               ASSERT( input. lookahead. back( ). iswellformed( ));
            }

            if( input. lookahead. size( ) &&
                input. lookahead. front( ). type == parsetable [k] )
            {
               ++ k; 
               while( parsetable [k] < 0 )
                  result. push_back( parsetable [ k ++ ] );
               result. push_back( parsetable [k] );
               return result;
            }
            
            ++ k;
            while( parsetable [k] < 0 )
               ++ k;
            ++ k; 
         }
      }
   }


   bool stateisempty( unsigned int ss )
   {
      return starts [ss] == starts [ss+1];
   }


   bool isstartlookahead( unsigned int entry, tokenizer& input )
   { 
      ASSERT( input. lookahead. size( ));

      entry += 2;  
      while( entrypoints [ entry ] >= 0 )
      {
         if( entrypoints [ entry ] == input. lookahead. front( ). type )
            return true;
         ++ entry;
      }
      return false;
   }

}
 

// The tokenizer must have the following features:
// It must have a field std::list< token > lookahead; 
// It must have a method void scan( ), which reads a token from somewhere
// and appends it to lookahead. scan( ) must always return a token,
// also when it reaches end of file, or when it is unable to read 
// input for some kind of reason. 
// It must have a method syntaxerror( ), which reports a syntax error
// to the user. 
// 
// The parser is called with the start symbol of the partial grammar
// that has to be parsed. 
// It uses the lookahead list of the tokenizer for returning its value.
// In case of a successful parse, lookahead starts with the start
// symbol. A second symbol need not be present. If there is a second
// symbol, then it is the lookahead symbol of the original start symbol. 
// The parser will read the lookahead only when it is necessary for
// deciding.
// 
// When an error occurred, and the parser reached a lookahead symbol
// while attempting to recover, the lookahead list equals this 
// lookahead symbol. 
// If the parser gave up, because more than
// recoverlength symbols were read, it returns a list of length 1 
// containing a recover symbol. 

// Setting recoverlength = 0 ensures that the parser will not try to
// recover. 


void parser( tokenizer& input,
      varstore & memory, tokentype start, unsigned int recoverlength )
{

   unsigned int errorcount = 0;
      // If errorcount > 0, then errors are not reported. 
      // Instead we assume that the previous recovery was not 
      // successful. 

   unsigned int entry = 0;
   while( entrypoints [ entry ] != -1 && entrypoints [ entry ] != start )
   {
      while( entrypoints [ entry ] != -1 )
         ++ entry;
      ++ entry;
   }

   if( entrypoints [ entry ] != start )
   {
      std::cout<< "could not find startsymbol " << start << "\n";
      ASSERT( false ); 
      exit(0);
   }

   std::list< unsigned int > states; 
   states. push_back( entrypoints [ entry + 1 ] );

   std::list< token > parsestack; 
 
   while( true ) 
   {
      ASSERT( states. size( ) == parsestack. size( ) + 1 );

#ifdef MAPH_DEBUG
      std::cout << "stack of states: "; 
      for( std::list< unsigned int > :: const_iterator
              p = states. begin( );
              p != states. end( );
              ++ p )
      {
         if( p != states. begin( ))
            std::cout << ", "; 
         std::cout << *p;
      }
      std::cout << "\n";

      std::cout << "stack of symbols: "; 
      for( std::list< token > :: const_iterator
              p = parsestack. begin( );
              p != parsestack. end( );
              ++ p )
      {
         if( p != parsestack. begin( ))
            std::cout << ", ";
         std::cout << *p;
      }
      std::cout << "\n";

      if( input. lookahead. size( ))
         std::cout << "lookahead: " << input. lookahead. front( ) << "\n";
#endif
      // We will check if we are in an accepting state. 
      // The parse stack must have size 1, and contain the 
      // start symbol of the grammar.

      if( parsestack. size( ) == 1 && 
          parsestack. front( ). type == entrypoints [ entry ] )
      {
         // This is a good start.
      
         // If we are in an empty state, we simply accept, and that's
         // the end of the story.

         if( stateisempty( states. back( )))
         {
            input. lookahead. splice( input. lookahead. begin( ),
                                      parsestack, parsestack. begin( ));
            
            return;  
         }

         // Otherwise, we check whether lookahead is one of the 
         // lookahead symbols of the start symbol. 
                   
         if( input. lookahead. size( ) == 0 )
         {
            input. scan( );
            ASSERT( input. lookahead. size( ));
            ASSERT( input. lookahead. back( ). iswellformed( ));
         }

         if( isstartlookahead( entry, input )) 
         {
            // This means that we accept. We move the start symbol
            // to the lookahead and quit.

            input. lookahead. splice( input. lookahead. begin( ),
                                     parsestack, parsestack. begin( ));
            return; 
         }
 
         // Otherwise we simply continue, and let things go their way.
         // This does not necessarily imply that there will be an error.
         // It is also possible that the parser will continue.
      }
       
      std::list< int > actions = decideaction( states. back( ), input );

      // If we have reductions, we try to perform them:
      // If we manage to make a reduction, we clear actions,
      // so that we will come out of this loop:

      while( actions. size( ) > 1 ) 
      {
         ASSERT( actions. front( ) < 0 );
         unsigned int rule = - actions. front( ) - 10000;

#ifdef MAPH_DEBUG
         std::cout << "attempting to reduce rule " << rule << "\n";
#endif

         try
         {
            switch( rule ) 
            {
case 0:
   reduction_0( parsestack, parsestack. end( ) - 2, parsestack. end( ) - 2, parsestack. end( ) - 1 );
   break;
case 1:
   reduction_1( parsestack, parsestack. end( ) - 2, parsestack. end( ) - 2, parsestack. end( ) - 1 );
   break;
case 2:
   reduction_2( parsestack, parsestack. end( ) - 0 );
   break;
case 3:
   reduction_3( parsestack, parsestack. end( ) - 2, parsestack. end( ) - 2, parsestack. end( ) - 1 );
   break;
case 4:
   reduction_4( parsestack, parsestack. end( ) - 4, parsestack. end( ) - 4, parsestack. end( ) - 3, parsestack. end( ) - 2, parsestack. end( ) - 1 );
   break;
case 5:
   reduction_5( parsestack, parsestack. end( ) - 5, parsestack. end( ) - 5, parsestack. end( ) - 4, parsestack. end( ) - 3, parsestack. end( ) - 2, parsestack. end( ) - 1 );
   break;
case 6:
   reduction_6( parsestack, parsestack. end( ) - 2, parsestack. end( ) - 2, parsestack. end( ) - 1 );
   break;
case 7:
   reduction_7( parsestack, parsestack. end( ) - 3, parsestack. end( ) - 3, parsestack. end( ) - 2, parsestack. end( ) - 1 );
   break;
case 8:
   reduction_8( parsestack, parsestack. end( ) - 3, parsestack. end( ) - 3, parsestack. end( ) - 2, parsestack. end( ) - 1 );
   break;
case 9:
   reduction_9( parsestack, parsestack. end( ) - 1, parsestack. end( ) - 1 );
   break;
case 10:
   reduction_10( parsestack, parsestack. end( ) - 3, parsestack. end( ) - 3, parsestack. end( ) - 2, parsestack. end( ) - 1 );
   break;
case 11:
   reduction_11( parsestack, parsestack. end( ) - 3, parsestack. end( ) - 3, parsestack. end( ) - 2, parsestack. end( ) - 1 );
   break;
case 12:
   reduction_12( parsestack, parsestack. end( ) - 1, parsestack. end( ) - 1 );
   break;
case 13:
   reduction_13( parsestack, parsestack. end( ) - 2, parsestack. end( ) - 2, parsestack. end( ) - 1 );
   break;
case 14:
   reduction_14( parsestack, parsestack. end( ) - 2, parsestack. end( ) - 2, parsestack. end( ) - 1 );
   break;
case 15:
   reduction_15( parsestack, parsestack. end( ) - 1, parsestack. end( ) - 1 );
   break;
case 16:
   reduction_16( parsestack, parsestack. end( ) - 2, parsestack. end( ) - 2, parsestack. end( ) - 1 );
   break;
case 17:
   reduction_17( parsestack, parsestack. end( ) - 3, parsestack. end( ) - 3, parsestack. end( ) - 2, parsestack. end( ) - 1 );
   break;
case 18:
   reduction_18( parsestack, parsestack. end( ) - 1, parsestack. end( ) - 1 );
   break;
case 19:
   reduction_19( parsestack, parsestack. end( ) - 1, parsestack. end( ) - 1 );
   break;
case 20:
   reduction_20( parsestack, parsestack. end( ) - 4, parsestack. end( ) - 4, parsestack. end( ) - 3, parsestack. end( ) - 2, parsestack. end( ) - 1 );
   break;
case 21:
   reduction_21( parsestack, parsestack. end( ) - 1, parsestack. end( ) - 1 );
   break;
case 22:
   reduction_22( parsestack, parsestack. end( ) - 3, parsestack. end( ) - 3, parsestack. end( ) - 2, parsestack. end( ) - 1 );
   break;

            default:
	       std::cout << "unknown rule!\n";
	       exit(0); 
            }

#ifdef MAPH_DEBUG
            std::cout << "reduced rule " << rule << "\n";
#endif

            ASSERT( parsestack. size( )); 

            ASSERT( states. size( ) >= parsestack. size( ));

            while( states. size( ) > parsestack. size( ))
               states. pop_back( );

            // We now need to shift the lhs of the rule.
            // We do not like to copy tokens, because their attributes
            // can be big without borders. Copying can be avoided 
            // using list specific operations. 

            std::list< token > :: iterator p = parsestack. end( ) - 1;
            input. lookahead. splice( input. lookahead. begin( ), 
                                      parsestack, p );
               // Now the back of the parsestack is in front of lookahead.
               // It is possible that lookahead has a length of two now.

            actions = decideaction( states. back( ), input ); 

#if 0
            for( std::list< int > :: const_iterator
                     p = actions. begin( );
                     p != actions. end( );
                     ++ p )
            {
               std::cout << *p << "\n";
            }
#endif 

            // The action may contain reductions, but we are interested
            // in the push. In earlier versions, I assumed that actions 
            // necessarily contains only a single push, but this assumption
            // turned out wrong.  

            while( actions. size( ) > 1 )
            {
               ASSERT( actions. front( ) < 0 );
               actions. pop_front( );
            }

            // Now the action list should consist of a single push:

            ASSERT( actions. size( ) == 1 && actions. front( ) > 0 );

#ifdef MAPH_DEBUG
            std::cout << "goto " << actions. front( ) - 10000 << "\n"; 
#endif
            // We do not carry out the goto. 

            ++ errorcount;
         }
         catch( refused ref )
         {
#ifdef MAPH_DEBUG
            std::cout << "rule " << rule << " refused\n";
#endif
            actions. pop_front( );
               // We are not going to be sad about the refusal. We 
               // simply try the next in line.
         }
      }   
 
      if( actions. size( ) == 1 && actions. front( ) > 0 ) 
      {
         ASSERT( input. lookahead. size( ) == 1 || 
                 input. lookahead. size( ) == 2 );
         actions. front( ) -= 10000;
#ifdef MAPH_DEBUG
         std::cout << "shifting " << input. lookahead. front( ) << "\n"; 
#endif
 
         if( errorcount > 0 ) 
	    -- errorcount; 

         parsestack. splice( parsestack. end( ), 
                             input. lookahead, input. lookahead. begin( ));
            // This puts the symbol on the parsestack without moving it. 

         states. push_back( actions. front( ));

      }
      else
      {
         // If there is something left in actions, it is an error.

         ASSERT( actions. size( ) == 1 && actions. front( ) == 0 );
         ASSERT( input. lookahead. size( ));

#ifdef MAPH_DEBUG
        std::cout << "error!\n"; 
#endif

         // It is the responsability of the tokenizer to process the error:

         input. syntaxerror( );
 
         // Recovery will be the level at which we can recover.
         // As long as we did not recover, it will be -1.
 
         int recovery = -1; 
         unsigned int ignoredtokens = 0;

         while( recovery < 0 && ! isstartlookahead( entry, input ) && 
                ignoredtokens < recoverlength )
         {
            // Our approach is simple and inefficient, we look for
            // states that can push a recovery symbol, and after that
            // would be able to push the current lookahead symbol.

            std::list< unsigned int > :: const_iterator p = states. begin( );

            for( unsigned int k = 0; k < states. size( ); ++ k )
            {
               input. lookahead. push_front( token( tkn__recover ));
               actions = decideaction( *p, input );
               input. lookahead. pop_front( );

               if( actions. size( ) == 1 && actions. front( ) > 0 )
               {
                  // Recover transition is possible. 

                  unsigned int trans = actions. front( ) - 10000; 
                  actions = decideaction( trans, input );
               
                  if( actions. size( ) == 1 && actions. front( ) > 0 )
                     recovery = k;
                        // We remember that recovery was possible.
                        // If more than recovery is possible, we will
                        // remember the highest in recovery. 
               }
            
               ++ p;
            }
       
            if( recovery < 0 )
            {
               input. lookahead. clear( );
               ++ ignoredtokens;
               input. scan( );
               ASSERT( input. lookahead. size( )); 
               ASSERT( input. lookahead. back( ). iswellformed( ));
            }
         }

#ifdef MAPH_DEBUG 
         std::cout << "recovery = " << recovery << "\n";
         if( input. lookahead. size( ))
         {
            std::cout << "lookahead = ";
            std::cout << input. lookahead. front( ) << "\n";
         }
#endif

         if( ignoredtokens >= recoverlength ) 
         {
            // That was it. Game over. We lost.

            input. lookahead. clear( );
            input. lookahead. push_front( tkn__recover );
            return;
         }

         if( isstartlookahead( entry, input ))
         {
            // We reached a lookahead symbol of the grammar. 
            // We admit our defeat. 

            return;
         } 

         while( states. size( ) > recovery + 1 )
         {
            states. pop_back( );
            parsestack. pop_back( ); 
         }

         input. lookahead. push_front( token( tkn__recover ));
         actions = decideaction( states. back( ), input );
         input. lookahead. pop_front( );

         ASSERT( actions. size( ) == 1 && actions. front( ) > 0 );
         actions. front( ) -= 10000;
       
         states. push_back( actions. front( ));
         parsestack. push_back( token( tkn__recover ));

         actions = decideaction( states. back( ), input );
     
         ASSERT( actions. size( ) == 1 && actions. front( ) > 0 );
         actions. front( ) -= 10000;

#ifdef MAPH_DEBUG
         std::cout << "recovering into state " << actions. front( );
         std::cout << " using token " << input. lookahead. front( ) << "\n";
#endif

         states. push_back( actions. front( ));
         parsestack. splice( parsestack. end( ),
                             input. lookahead, input. lookahead. begin( ));

         errorcount = 3;
      }
   }
}


